name: SITE.NAME
icon_name: favicon.ico
ga_profile_id: SITE.GA_PROFILE_ID
markdown: redcarpet
highlighter:
exclude: [ doc, Gemfile, Gemfile.lock, upload.sh, README.md ]
gems:
- jekyll-assets
- jekyll-sitemap
compress:
  css:  sass
  js:   uglifier
url: SITE.URL
