title: Ember Floating Mobile Buttons
theme: jekyll-theme-cayman
description: Stylish and easy to use Ember floating buttons
show_downloads: false
google_analytics: UA-116305706-1
sass-variables: variables